### ISSUE TITLE
Error code 3221226525 appears once

### ISSUE THREAD

**Issue by hyunjimoon** [tseyanglim/VST#2]
Another error code is discovered 3221226525. This gives me the license warning dialog only once (contrary to the previous error code in issue #1), it disappears and run calibration correctly in the second attempt. This error does not happens everytime, but around once in five runs. I am using the updated version Tom shared with the following comment. 
```
The expiration warning no longer uses a dialog. This means it's not visible unless you look in the .err log in %appdata%.
Running XPARALLEL
```

@tseyanglim do you know how to 1. turn off warning dialog and 2.run XPARALLEL?
```
Initialising <__main__.Script object at 0x00000130250F8640>
-----
Starting new log at Thu Oct  6 13:18:04 2022
Ready to work!
Initialising <__main__.Script object at 0x0000013025106950>
Initialising PrPr_main_opt!
Return code is 3221226525
Vensim! Trying again...
Payoff for PrPr_main_opt is -878.334, calibration complete!
Optimization complete - payoff is -878.334!
More work? Okay!
Initialising <__main__.RunScript object at 0x0000013025106950>
Traceback (most recent call last):
  File "C:\Users\amoon\Dropbox\WINcode\VST\VST Automation\VST Automation Example v2.py", line 349, in <module>
    compile_script(cf, RunScript, 'main', 'run', {}, logfile, chglist=[('main', 'opt')])
  File "C:\Users\amoon\Dropbox\WINcode\VST\VST Automation\VST Automation Example v2.py", line 164, in compile_script
    return mainscript.run_script(scriptname, controlfile, subdir, logfile)
  File "C:\Users\amoon\Dropbox\WINcode\VST\VST Automation\VST Automation Example v2.py", line 116, in run_script
    return run_vensim_script(scriptname, controlfile['vensimpath'], 10, logfile)
  File "C:\Users\amoon\Dropbox\WINcode\VST\VST Automation\VST Automation Example v2.py", line 274, in run_vensim_script
    subprocess.run(f"{vensimpath} \"./{scriptname}.cmd\"", check=True)
  File "C:\Users\amoon\Miniconda3\envs\VST\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\amoon\Miniconda3\envs\VST\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\amoon\Miniconda3\envs\VST\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] The parameter is incorrect

Process finished with exit code 1
```

**Comment by tseyanglim** [comment]
I have seen that one a couple of times, I don't know what's causing it but it's precisely these semi-random / non-systematic weird results that the `proc.returncode` check is supposed to catch. So while it's a Vengine issue, it should not undermine the `run_vengine_script` code working correctly. (As the extended comment on the function notes, Vengine has a lot of random bugs that the function is meant to catch.)

Running XPARALLEL - that's done through the `.voc` file, it's one of the options for Multiple Start (like RANDOM or RRANDOM).

**Comment by hyunjimoon** [comment]
Unfortunately, it seems XPARALLEL is not documented? From Hazhir's code, XParallel seems to be a new option, not documented in vensim yet. Do you know where this should be reported? Tony?
```
:MULTIPLE_START=XParallel
```
<img width="548" alt="image" src="https://user-images.githubusercontent.com/30194633/194383475-cb40e331-1394-4ac3-bdc3-06d3dc6cddb1.png">

**Comment by tseyanglim** [comment]
It's 'documented' in the README of the new Vengine (in the shared drive) but nowhere else for the moment. No need to report I think, Tom will incorporate it eventually.
